# Numpy 
- Numpy means numerical python
- Numpy is fast then simple python
- Manipulation perform on raw data
- Numpy was not made on static typing so for that we will use np package

In [1]:
%pip install nptyping beartype


  Obtaining dependency information for beartype from https://files.pythonhosted.org/packages/46/8a/a90fe78c73958340ed6b6ab128a10598ad5f0ff57537ad17f6ccd1ad830b/beartype-0.16.4-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
    --------------------------------------- 10.2/819.1 kB ? eta -:--:--
    --------------------------------------- 10.2/819.1 kB ? eta -:--:--
    --------------------------------------- 10.2/819.1 kB ? eta -:--:--
    --------------------------------------- 10.2/819.1 kB ? eta -:--:--
   - ------------------------------------- 30.7/819.1 kB 119.1 kB/s eta 0:00:07
   - ------------------------------------- 30.7/819.1 kB 119.1 kB/s eta 0:00:07
   - ------------------------------------- 30.7/819.1 kB 119.1 kB


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Scaler value


In [7]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

display(a) # prints

array(1000)

In [8]:
display(a.shape) # prints the shape of the object () = 0 -Dimensional

()

In [9]:
display(a.dtype) # prints the dtype of the object

dtype('int32')

In [10]:
display(type(a)) 

numpy.ndarray

In [11]:
display(a.ndim) # prints the number of dimensions

0

In [12]:
display(a.size) # prints the size of the object

1

In [13]:
display(a.itemsize) # prints the itemsize of the object

4

# Vector Type
We can only store upto 5D dimension 


In [14]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # we pass list here, object to store [1,2,3,4] = vector type

display(f"object {a}") # prints
display(f"object shape {a.shape}") # prints the shape of the object () = 0 Dimension
display(f"object dtype {a.dtype}") # prints the dtype of the object
display(f"object type with global function {type(a)}") 
display(f"object dimension {a.ndim}") # prints the number of dimensions
display(f"object size {a.size}") # prints the size of the object
display(f"object item size (size of memory) {a.itemsize}") # prints the itemsize of the object

'object [1 2 3 4]'

'object shape (4,)'

'object dtype int32'

"type of a <class 'numpy.ndarray'>"

'object dimension 1'

'object size 4'

'object item size 4'

### For help about any function

In [16]:
help(a.itemsize)

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |
 |  Built-in subclasses:
 |      bool
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __ceil__(..

# Matrix


In [20]:
import numpy as np

data = [[0,1,2,3],[4,5,6,7],    #this is 2D array
        [8,9,10,11],[12,13,14,15]]

a : np.ndarray = np.array(data) # object to store

display(f"object {a}") # prints
display(f"object shape {a.shape}") # prints the shape of the object () = 0 Dimension
display(f"object dtype {a.dtype}") # prints the dtype of the object
display(f"object type with global function {type(a)}") 
display(f"object dimension {a.ndim}") # prints the number of dimensions
display(f"object size {a.size}") # prints the size of the object
display(f"object item size (size of memory) {a.itemsize}")  # prints the itemsize of the object

'object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]\n [12 13 14 15]]'

'object shape (4, 4)'

'object dtype int32'

"object type with global function <class 'numpy.ndarray'>"

'object dimension 2'

'object size 16'

'object item size (size of memory) 4'

## So what to do when we have more than 5D dimensions?
To handle it fastly we use numpy

# Numpy with NDArray typing support
Numpy new way to handle more dimensions

In [30]:
from nptyping import NDArray, Shape, UInt16

data : NDArray[Shape["10"], UInt16] = np.arange(10)
data1 : NDArray[Shape["10"], UInt16] = np.arange(1,11)

display(data)
display(data1)
display(data1 + 5) #doesnot change an original array - numpy easy way and fast
display(data1)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
 # same plus operation using traditional way
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
# print(d1 + 5) #Error
[i+5 for i in d1] #traditional way - it is time consuming

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [33]:
#with numpy
%%time

data2 : NDArray[Shape["10"], UInt16] = np.arange(1,2000000)

data2 + 5 #doesnot change an original array - numpy easy way and fast


CPU times: total: 15.6 ms
Wall time: 9.06 ms


array([      6,       7,       8, ..., 2000002, 2000003, 2000004])

In [44]:
# through traditional way
%%time

data3 : list[int] = list(range(1,1000000))
[i + 5 for i in data3] #list comprehensive

Time taken to run the code is :  0.19343066215515137


In [ ]:
# through traditional way
import time
# %%time

start_time  = time.time()
data3 : list[int] = list(range(1,1000000))
[i + 5 for i in data3] #list comprehensive
end_time = time.time()

print("Time taken to run the code is : ", end_time - start_time)

# Numpy advance operations vs list operations

In [46]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])

#now we want to update the list 
data[5:11] = 1000 #normal python list
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [8]:
import numpy as np
from nptyping import NDArray, Shape, UInt16


ndata : NDArray[Shape["20"], UInt16] = np.arange(1,21)
print(ndata)
print(ndata[5:11])

ndata[5:11] = 1000 #it will change the numbers from the list 
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Num 1D function

In [6]:
from nptyping import Bool
#  selection true value through numpy
state_bank : NDArray[Shape["10"], Bool] = np.array([1,7,8,10])

# [1,7,8,10]
# [True, False, False, True]

select : NDArray[Shape["10"],Bool] = np.array([True, False, False, True]) #boolean array
state_bank[select] #it will compare the [1,7,8,10] and [True, False, False, True] and only return those value that are true

array([ 1, 10])

### we can create the above boolean array from so many ways

In [7]:
state_bank : NDArray[Shape["10"], Bool] = np.array([1,7,8,10])
state_bank % 2 == 0

array([False, False,  True,  True])

In [8]:
#snapchat filters are created through this true and false
state_bank : NDArray[Shape["10"], Bool] = np.array([1,7,8,10])
state_bank[state_bank % 2 == 0] # state_bank % 2 == 0 return [False, False,  True,  True] so when we pass state_bank[[False, False,  True,  True]] so it will compare the state_bank array with [False, False,  True,  True] and return value where there is true i.e 8, 10 here


array([ 8, 10])

In [14]:
import numpy as np
from nptyping import NDArray, Shape, UInt16

state_bank : NDArray[Shape["10"], UInt16]= np.array([1,7,8,10])

ubl_bank : NDArray[Shape["10"],UInt16] = np.random.randint(1,100,20) #generate numbers between 1 and 100 and generate total elements 20

display(state_bank)
display(ubl_bank)


array([ 1,  7,  8, 10])

array([95, 95, 15, 62, 55, 74, 92,  1, 75, 78, 20, 74, 61, 68, 54, 87, 62,
       89, 25, 78])

In [15]:
#       4items (willbe) search from 20 items
np.in1d(state_bank, ubl_bank) #np.in1d(array_on_which_you_want_to_perform_search, array_through_which_you_want_to_search)

array([ True, False, False, False])

In [16]:
state_bank[np.in1d(state_bank, ubl_bank)]

array([1])

In [17]:
np.intersect1d(state_bank, ubl_bank) #now we dont have to manually write and compare them

array([1])

In [21]:
x : NDArray[Shape["4"], UInt16] = np.array([1,2,3,4,5])
y : NDArray[Shape["4"], UInt16] = np.array([5,6,2,8,3])

display(x)
display(y)
np.where(x > y, x, y) #where is used for comparison

array([1, 2, 3, 4, 5])

array([5, 6, 2, 8, 3])

array([5, 6, 3, 8, 5])

# Create a Numpy array

In [26]:
from typing import Any

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)  #2D array - 2x3

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                      [4, 5]]) 
print(a) # 2D array - 2x2

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                    ["B"]]) 
print(a) # 2D array - 2x1

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [28]:
# we can also write like that
from typing import Any

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)  #2D array - 2x3

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2],
                                                      [4, 5]]) 
print(a) # 2D array - 2x2

a : NDArray[Shape["*, *"], Any] = np.array([["A"],
                                                    ["B"]]) 
print(a) # 2D array - 2x1

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [29]:
np.who()

Name            Shape            Bytes            Type

_               5                20               int32
__              5                20               int32
___             5                20               int32
state_bank      4                16               int32
ubl_bank        20               80               int32
select          4                4                bool
_6              2                8                int32
_7              4                4                bool
_8              2                8                int32
_9              4                4                bool
_11             4                4                bool
_13             4                4                bool
_15             4                4                bool
_16             1                4                int32
_17             1                4                int32
x               5                20               int32
y               5                20               int3

# Create any Dimension array

In [33]:
# 1D shape
a : NDArray[Shape["Size, Size"], UInt16] = np.arange(1,5)
print(a)

# 2D shape
a : NDArray[Shape["Size, Size"], UInt16] = np.arange(3*3).reshape(3,3)
print(a)

[1 2 3 4]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
# 2D shape with 5 rows
a : NDArray[Shape["Size, Size"], UInt16] = np.arange(5*3).reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
#3D shape
a : NDArray[Shape["Size, Size, Size"], UInt16] = np.arange(3*3*3).reshape(3,3,3)
print(a)

#performing slicing on it
a[::2,::,::]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
a : NDArray[Shape["Size, Size, Size"], UInt16] = np.arange(3*3*3).reshape(3,3,3)
a[a%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [41]:
#convert into numpy array
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [42]:
# it will generate array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
#array of zeros with dimension
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
# it will generate array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
#array of ones with dimension
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
a : NDArray[Shape["Size, Size"], UInt16] = np.arange(5*3).reshape(5,3)
np.ones_like(a) #it will create a copy of already existing array i.e a here and create ones array of that array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
a : NDArray[Shape["Size, Size"], UInt16] = np.arange(5*2*2).reshape(5,2,2)
print(a)
print("===================")
a[[0,-1],::,::] # 0 = first, -1 = last -> means from the above whole array of a we select 0 image and last (-1) image 

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [58]:
ndata : NDArray[Shape["20"], UInt16] = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax()) #index value of largest number
print(ndata.argmin()) #index value of minimum number
print(ndata.mean()) #
print(ndata.std()) #
print(ndata.sum()) #
print(ndata.cumsum()) #

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
0
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
